### ISSUE TITLE
BDOdecrypt for langVersion 141 (client version 661) not working...

### ISSUE THREAD

**Issue by divStar** [AMGarkin/BDOcrypt#2] opened 2018-08-30 04:55 UTC
... or I am making a mistake somewhere...

I've got the NA/EU client with ads folder and the following files in it:
- languagedata_en.loc
- languagedata_de.loc
- languagedata_es.loc

I am trying to decrypt the first one. langVersion.dat suggests the localization files are provided in version "141" (the client itself is version 661).

When I try the following:
`$ ./BDO_decrypt ads/languagedata_en.loc ads/languagedata_en.txt`
I get:
> ERROR: Input data are corrupted or incomplete.

Even though the client itself seems to work just fine and everything in it seems properly translated (as in: the translation properly appears as expected).

Do you happen to know why I am having this issue? Does BDOdecrypt not support this version (or is it perhaps "too new" or "too old"?)? I tried v1.0 and v2.0 as well as the latest version - none of them were able to decrypt the localization file.

**Comment by AMGarkin** [comment] 2018-08-30 15:04
Current version of localization files on official NA/EU server is v281 and client itself is v872. So you are trying to decrypt files in old format. Try to use the first release of this tool:
https://github.com/AMGarkin/BDOcrypt/releases/tag/1.0

If it still dont work, can you share your localization files, so I can take a look what format it uses?

**Comment by skilledpt** [comment] 2018-12-16 13:25
did u got any luck with this? i dont get any error with version 1.0 but the text dont change anw

**Comment by skilledpt** [comment] 2018-12-16 15:13
i changed both .loc and .txt file on the client, but the name of the item doesnt change

**Comment by AMGarkin** [comment] 2018-12-17 14:58
@skilledpt can you upload your loc file somewhere and send me a link? I'll try to figure out why it doesn't work with your version.

**Comment by skilledpt** [comment] 2018-12-18 04:37
@AMGarkin the original one right?
I have 2 .loc files in my paz, 1 in stringtable folder and other in stringtable>en, one is bigger than the other.
I uploaded both.
[https://www68.zippyshare.com/v/ldIzL7fg/file.html](https://www68.zippyshare.com/v/ldIzL7fg/file.html)

**Comment by AMGarkin** [comment] 2018-12-18 09:19
@skilledpt Both files can be correctly decrypted using v1.0 (https://github.com/AMGarkin/BDOcrypt/releases/tag/1.0).

What are you trying to do? If you use it for BDO-GuildQuestMod, you should use old version as well. Here are all old tools you need:
https://www36.zippyshare.com/v/3fcXiDMg/file.html

**Comment by skilledpt** [comment] 2018-12-18 12:10
@AMGarkin  Like i said i had no problem decrypting or encrypting, i already use version 1.0. 
The problem is after encrypt back, nothing changes in game. Im trying to change a item name, and somethings in pearlshop.

And i don't use GuildQuestMod btw.

**Comment by AMGarkin** [comment] 2018-12-18 16:59
If game doesn't load texts from .loc files, it probably reads texts from files inside of .paz archives, so you will need some other tool such as [this one](https://www.undertow.club/threads/bdo-toolkit-a-net-modding-library-for-black-desert-online.12042/).

As this is not BDOdecrypt issue, I'm closing it.

**Closed as completed** 2018-12-18 17:00 UTC

**Comment by skilledpt** [comment] 2018-12-18 17:44
@AMGarkin what????
Im already using that tool, my .loc files and inside my paz....
I changed in datasheet it also dont change item name.
